ITEM.name = "Throwing Knife"
ITEM.description = "A small, sharpened piece of steel with some wire wrapped around it. Should hurt."
ITEM.model = "models/weapons/w_knife_t.mdl"
ITEM.class = "arccw_go_nade_knife"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_EOW}
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 1